export interface Product {
  id: number
  name: string
  price: number
  category: string
  categorySlug: string
  image: string
  description: string
  isNew?: boolean
}

export const products: Product[] = [
  {
    id: 1,
    name: "Aurora Gold Chandelier",
    price: 2450,
    category: "Chandeliers",
    categorySlug: "chandeliers",
    image: "/gold-modern-chandelier.jpg",
    description: "A luxurious modern gold chandelier that adds a touch of elegance to any room.",
    isNew: true,
  },
  {
    id: 2,
    name: "Luna Table Lamp",
    price: 450,
    category: "Table Lamps",
    categorySlug: "table-lamps",
    image: "/ceramic-table-lamp-beige.jpg",
    description: "Beige ceramic table lamp with a simple and eye-friendly design.",
  },
  {
    id: 3,
    name: "Modern Black Pendant",
    price: 890,
    category: "Pendant Lights",
    categorySlug: "pendant",
    image: "/black-pendant-light-minimal.jpg",
    description: "Matte black pendant light, perfect for modern dining rooms and kitchens.",
  },
  {
    id: 4,
    name: "Arc Floor Lamp",
    price: 1200,
    category: "Floor Lamps",
    categorySlug: "floor-lamps",
    image: "/arc-floor-lamp.jpg",
    description: "Elegant arched floor lamp providing ideal reading light.",
  },
  {
    id: 5,
    name: "Classic Crystal Chandelier",
    price: 3800,
    category: "Chandeliers",
    categorySlug: "chandeliers",
    image: "/crystal-chandelier-isolated.jpg",
    description: "Luxurious crystal chandelier with a classic design reflecting sophistication and refined taste.",
  },
  {
    id: 6,
    name: "Industrial Desk Lamp",
    price: 350,
    category: "Table Lamps",
    categorySlug: "table-lamps",
    image: "/industrial-desk-lamp.jpg",
    description: "Metal desk lamp with a practical and elegant industrial design.",
  },
  {
    id: 7,
    name: "Modern Ring Chandelier",
    price: 1850,
    category: "Chandeliers",
    categorySlug: "chandeliers",
    image: "/pendant-light-modern-isolated.jpg",
    description: "Modern chandelier with interlocking ring design and integrated LED lighting.",
    isNew: true,
  },
  {
    id: 8,
    name: "Wooden Floor Lamp",
    price: 950,
    category: "Floor Lamps",
    categorySlug: "floor-lamps",
    image: "/wooden-floor-lamp.jpg",
    description: "Floor lamp with natural wooden base and beige fabric shade.",
  },
  {
    id: 9,
    name: "Glass Ceiling Chandelier",
    price: 1100,
    category: "Chandeliers",
    categorySlug: "chandeliers",
    image: "/glass-ceiling-chandelier.jpg",
    description: "Ceiling chandelier with clear glass spheres and gold metal frame.",
  },
  {
    id: 10,
    name: "Brass Pendant Light",
    price: 620,
    category: "Pendant Lights",
    categorySlug: "pendant",
    image: "/brass-pendant-light.jpg",
    description: "Pendant light with shiny brass finish and geometric design.",
  },
  {
    id: 11,
    name: "Adjustable Reading Lamp",
    price: 280,
    category: "Table Lamps",
    categorySlug: "table-lamps",
    image: "/adjustable-reading-lamp.jpg",
    description: "Practical reading lamp with adjustable and movable arm.",
  },
  {
    id: 12,
    name: "Rustic Chandelier",
    price: 2100,
    category: "Chandeliers",
    categorySlug: "chandeliers",
    image: "/rustic-chandelier-wood-and-metal.jpg",
    description: "Rustic design chandelier made of wood and aged metal.",
  },
  {
    id: 13,
    name: "Gold Sputnik Chandelier",
    price: 2850,
    category: "Chandeliers",
    categorySlug: "chandeliers",
    image: "/gold-sputnik-chandelier-modern.jpg",
    description: "Modern sputnik design chandelier with multi-directional gold arms.",
    isNew: true,
  },
  {
    id: 14,
    name: "Blue Ceramic Side Lamp",
    price: 520,
    category: "Table Lamps",
    categorySlug: "table-lamps",
    image: "/blue-ceramic-table-lamp.jpg",
    description: "Side lamp with blue ceramic base featuring artistic hand-painted touches.",
  },
  {
    id: 15,
    name: "Clear Glass Pendant",
    price: 740,
    category: "Pendant Lights",
    categorySlug: "pendant",
    image: "/clear-glass-pendant-light.jpg",
    description: "Pendant light with clear glass shade and clean modern design.",
  },
  {
    id: 16,
    name: "Black Iron Floor Lamp",
    price: 1450,
    category: "Floor Lamps",
    categorySlug: "floor-lamps",
    image: "/black-iron-floor-lamp-tripod.jpg",
    description: "Floor lamp with tripod iron base and matte black finish.",
  },
  {
    id: 17,
    name: "Empire Crystal Chandelier",
    price: 4500,
    category: "Chandeliers",
    categorySlug: "chandeliers",
    image: "/empire-crystal-chandelier-luxury.jpg",
    description: "Luxurious empire-style chandelier studded with high-quality crystals.",
  },
  {
    id: 18,
    name: "Smart LED Desk Lamp",
    price: 680,
    category: "Table Lamps",
    categorySlug: "table-lamps",
    image: "/smart-led-desk-lamp.jpg",
    description: "Smart desk lamp with controllable LED lighting and USB charging port.",
  },
  {
    id: 19,
    name: "Industrial Copper Pendant",
    price: 560,
    category: "Pendant Lights",
    categorySlug: "pendant",
    image: "/industrial-copper-pendant-light.jpg",
    description: "Industrial design pendant light made of red copper with braided cord.",
  },
  {
    id: 20,
    name: "Marble Floor Lamp",
    price: 1850,
    category: "Floor Lamps",
    categorySlug: "floor-lamps",
    image: "/marble-floor-lamp-luxury.jpg",
    description: "Luxurious floor lamp with white marble base and shiny gold pole.",
  },
  {
    id: 21,
    name: "Modern Matte Black Chandelier",
    price: 1680,
    category: "Chandeliers",
    categorySlug: "chandeliers",
    image: "/modern-matte-black-chandelier.jpg",
    description: "Modern chandelier with matte black finish and simple geometric design.",
    isNew: true,
  },
  {
    id: 22,
    name: "Wooden Night Lamp",
    price: 290,
    category: "Table Lamps",
    categorySlug: "table-lamps",
    image: "/wooden-night-lamp-warm.jpg",
    description: "Small night lamp made of natural wood with comfortable warm lighting.",
  },
  {
    id: 23,
    name: "Triple Pendant Set",
    price: 1320,
    category: "Pendant Lights",
    categorySlug: "pendant",
    image: "/placeholder.svg?height=400&width=400",
    description: "Set of three pendant lights with coordinated design for dining tables.",
  },
  {
    id: 24,
    name: "Arched Marble Floor Lamp",
    price: 2200,
    category: "Floor Lamps",
    categorySlug: "floor-lamps",
    image: "/placeholder.svg?height=400&width=400",
    description: "Arched floor lamp with heavy marble base and elegant contemporary design.",
  },
]

export const categories = [
  { slug: "chandeliers", name: "Chandeliers", image: "/gold-modern-chandelier.jpg" },
  { slug: "floor-lamps", name: "Floor Lamps", image: "/arc-floor-lamp.jpg" },
  { slug: "pendant", name: "Pendant Lights", image: "/black-pendant-light-minimal.jpg" },
  { slug: "table-lamps", name: "Table Lamps", image: "/ceramic-table-lamp-beige.jpg" },
]
